import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './components/layout/header'
import Nav from './components/layout/nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Online Store',
  description: 'Generated by create next app',
}

interface IProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: IProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full max-w-7xl">
          <Header />
          <Nav />
          <div className="absolute left-0 border-b border-gray-200 w-vw"></div>
          {children}
        </div>
      </body>
    </html>
  )
}
